#! /bin/bash

function jsonValue() {
KEY=$1
num=$2
awk -F":" '{for(i=1;i<=NF;i++){if($i~/'$KEY'\042/){print $(i+1)}}}' | tr -d '",' | sed -n $((${num}+1))p | tr -d ' '
}


SRC_DIR=src
OUT_DIR=exe
LIB_DIR=samiam
CP=${LIB_DIR}:${LIB_DIR}/inflib.jar:include/*
JAVA=java

CONFIG_FILE="config.json"

odd_name=${name}".odd"
sdd_name=${name}".sdd"
vtree_name=${name}".vtree"

mkdir -p ${OUT_DIR}
make

${JAVA} -Xmx150g -cp ${CP}:${OUT_DIR} RunCompiler ${CONFIG_FILE}
${JAVA} -Xmx150g -cp ${CP}:${OUT_DIR} TestOdd ${CONFIG_FILE}

cd src/sdd/
python convert_to_sdd.py ../../${CONFIG_FILE}
cd ../../
