#! /bin/bash

SRC_DIR=src
OUT_DIR=exe
LIB_DIR=samiam
CP=${LIB_DIR}:${LIB_DIR}/inflib.jar:include/*
JAVA=java

CONFIG_FILE="config.json"

mkdir -p ${OUT_DIR}
make

${JAVA} -Xmx150g -cp ${CP}:${OUT_DIR} RunCompiler ${CONFIG_FILE}
${JAVA} -Xmx150g -cp ${CP}:${OUT_DIR} TestOdd ${CONFIG_FILE}

cd src/sdd/
python convert_to_sdd.py ../../${CONFIG_FILE}
cd ../../
